spring:
  application:
    name: oauth2-spring-webflux
  mvc:
    view:
      suffix: .html   
  main:
    allow-bean-definition-overriding: true   
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: cleint-secret
            scope:
            - openid
            - email
            redirect-uri: http://localhost:8181/home
            authorization-grant-type: authorization_code
server:
  port: 8181 

logging:
  level:
    org: 
      springframework:
        security: DEBUG 
          
          
      
